/* Auto-generated by genmsg_cpp for file /tmp/buildd/ros-electric-multimaster-experimental-0.1.9/debian/ros-electric-multimaster-experimental/opt/ros/electric/stacks/multimaster_experimental/app_manager/srv/StartApp.srv */
#ifndef APP_MANAGER_SERVICE_STARTAPP_H
#define APP_MANAGER_SERVICE_STARTAPP_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace app_manager
{
template <class ContainerAllocator>
struct StartAppRequest_ {
  typedef StartAppRequest_<ContainerAllocator> Type;

  StartAppRequest_()
  : name()
  {
  }

  StartAppRequest_(const ContainerAllocator& _alloc)
  : name(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  name;


private:
  static const char* __s_getDataType_() { return "app_manager/StartAppRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "c1f3d28f1b044c871e6eff2e9fc3c667"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "07c2c0d81a44b3d573187630fa526c81"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
string name\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, name);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, name);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(name);
    return size;
  }

  typedef boost::shared_ptr< ::app_manager::StartAppRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::app_manager::StartAppRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StartAppRequest
typedef  ::app_manager::StartAppRequest_<std::allocator<void> > StartAppRequest;

typedef boost::shared_ptr< ::app_manager::StartAppRequest> StartAppRequestPtr;
typedef boost::shared_ptr< ::app_manager::StartAppRequest const> StartAppRequestConstPtr;


template <class ContainerAllocator>
struct StartAppResponse_ {
  typedef StartAppResponse_<ContainerAllocator> Type;

  StartAppResponse_()
  : started(false)
  , error_code(0)
  , message()
  , namespace()
  {
  }

  StartAppResponse_(const ContainerAllocator& _alloc)
  : started(false)
  , error_code(0)
  , message(_alloc)
  , namespace(_alloc)
  {
  }

  typedef uint8_t _started_type;
  uint8_t started;

  typedef int32_t _error_code_type;
  int32_t error_code;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  message;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _namespace_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  namespace;


private:
  static const char* __s_getDataType_() { return "app_manager/StartAppResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "29589baf2876ff624d4cb5688c12265e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "07c2c0d81a44b3d573187630fa526c81"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
bool started\n\
\n\
\n\
int32 error_code\n\
\n\
string message\n\
\n\
string namespace\n\
\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, started);
    ros::serialization::serialize(stream, error_code);
    ros::serialization::serialize(stream, message);
    ros::serialization::serialize(stream, namespace);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, started);
    ros::serialization::deserialize(stream, error_code);
    ros::serialization::deserialize(stream, message);
    ros::serialization::deserialize(stream, namespace);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(started);
    size += ros::serialization::serializationLength(error_code);
    size += ros::serialization::serializationLength(message);
    size += ros::serialization::serializationLength(namespace);
    return size;
  }

  typedef boost::shared_ptr< ::app_manager::StartAppResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::app_manager::StartAppResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StartAppResponse
typedef  ::app_manager::StartAppResponse_<std::allocator<void> > StartAppResponse;

typedef boost::shared_ptr< ::app_manager::StartAppResponse> StartAppResponsePtr;
typedef boost::shared_ptr< ::app_manager::StartAppResponse const> StartAppResponseConstPtr;

struct StartApp
{

typedef StartAppRequest Request;
typedef StartAppResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct StartApp
} // namespace app_manager

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::app_manager::StartAppRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::app_manager::StartAppRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::app_manager::StartAppRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const  ::app_manager::StartAppRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::app_manager::StartAppRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "app_manager/StartAppRequest";
  }

  static const char* value(const  ::app_manager::StartAppRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::app_manager::StartAppRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
string name\n\
\n\
";
  }

  static const char* value(const  ::app_manager::StartAppRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::app_manager::StartAppResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::app_manager::StartAppResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::app_manager::StartAppResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "29589baf2876ff624d4cb5688c12265e";
  }

  static const char* value(const  ::app_manager::StartAppResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x29589baf2876ff62ULL;
  static const uint64_t static_value2 = 0x4d4cb5688c12265eULL;
};

template<class ContainerAllocator>
struct DataType< ::app_manager::StartAppResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "app_manager/StartAppResponse";
  }

  static const char* value(const  ::app_manager::StartAppResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::app_manager::StartAppResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
bool started\n\
\n\
\n\
int32 error_code\n\
\n\
string message\n\
\n\
string namespace\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::app_manager::StartAppResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::app_manager::StartAppRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.name);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StartAppRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::app_manager::StartAppResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.started);
    stream.next(m.error_code);
    stream.next(m.message);
    stream.next(m.namespace);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StartAppResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<app_manager::StartApp> {
  static const char* value() 
  {
    return "07c2c0d81a44b3d573187630fa526c81";
  }

  static const char* value(const app_manager::StartApp&) { return value(); } 
};

template<>
struct DataType<app_manager::StartApp> {
  static const char* value() 
  {
    return "app_manager/StartApp";
  }

  static const char* value(const app_manager::StartApp&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<app_manager::StartAppRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "07c2c0d81a44b3d573187630fa526c81";
  }

  static const char* value(const app_manager::StartAppRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<app_manager::StartAppRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "app_manager/StartApp";
  }

  static const char* value(const app_manager::StartAppRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<app_manager::StartAppResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "07c2c0d81a44b3d573187630fa526c81";
  }

  static const char* value(const app_manager::StartAppResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<app_manager::StartAppResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "app_manager/StartApp";
  }

  static const char* value(const app_manager::StartAppResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // APP_MANAGER_SERVICE_STARTAPP_H

